### ISSUE TITLE
import fails

### ISSUE THREAD

**Issue by beckermr** [conda-forge/halotools-feedstock#5]
Issue:

I appears halotools depends on some other version of astropy?

```bash
(anl) localhost:Desktop Matt$ python -c "import halotools.mock_observables"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.7/site-packages/halotools/mock_observables/__init__.py", line 8, in <module>
    from .group_identification import *
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.7/site-packages/halotools/mock_observables/group_identification/__init__.py", line 6, in <module>
    from .fof_groups import FoFGroups
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.7/site-packages/halotools/mock_observables/group_identification/fof_groups.py", line 10, in <module>
    from ..pair_counters.pairwise_distance_xy_z import pairwise_distance_xy_z
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.7/site-packages/halotools/mock_observables/pair_counters/__init__.py", line 5, in <module>
    from .npairs_3d import npairs_3d
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.7/site-packages/halotools/mock_observables/pair_counters/npairs_3d.py", line 11, in <module>
    from .cpairs import npairs_3d_engine
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.7/site-packages/halotools/mock_observables/pair_counters/cpairs/__init__.py", line 12, in <module>
    from .npairs_per_object_3d_engine import npairs_per_object_3d_engine
  File "halotools/mock_observables/pair_counters/cpairs/npairs_per_object_3d_engine.pyx", line 10, in init halotools.mock_observables.pair_counters.cpairs.npairs_per_object_3d_engine
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.7/site-packages/halotools/utils/__init__.py", line 7, in <module>
    from .io_utils import *
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.7/site-packages/halotools/utils/io_utils.py", line 5, in <module>
    from astropy.extern.six.moves import urllib
ModuleNotFoundError: No module named 'astropy.extern.six'
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/Matt/miniconda3/envs/anl:
#
# Name                    Version                   Build  Channel
absl-py                   0.9.0                    py37_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
anyjson                   0.3.3                 py37_1001    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
appnope                   0.1.0                 py37_1000    conda-forge
argon2_cffi               19.1.0          py37h0b31af3_1000    conda-forge
arrow                     0.15.5                   py37_0    conda-forge
aspy.yaml                 1.3.0                      py_0    conda-forge
asteval                   0.9.16             pyh5ca1d4c_0    conda-forge
astropy                   4.0              py37h0b31af3_1    conda-forge
attrs                     19.3.0                     py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bcrypt                    3.1.7            py37h0b31af3_0    conda-forge
beautifulsoup4            4.8.2                    py37_0    conda-forge
binutils-meta             1.0.4                         0    conda-forge
black                     19.10b0                  py37_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blosc                     1.17.0               h6de7cb9_1    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
c-compiler                1.0.4                h1239861_0    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cached-property           1.5.1                      py_0    conda-forge
camb                      1.1.0            py37ha91d4f2_1    conda-forge
cctools                   927.0.2              h5ba7a2e_3    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2           py37h33e799b_0    conda-forge
cfgv                      2.0.1                      py_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
clang                     9.0.1           default_hf57f61e_0    conda-forge
clang_osx-64              9.0.1                h05bbb7f_0    conda-forge
clangxx                   9.0.1           default_hf57f61e_0    conda-forge
clangxx_osx-64            9.0.1                h05bbb7f_0    conda-forge
click                     7.0                        py_0    conda-forge
cmake                     3.16.2               hd28f656_1    conda-forge
cmarkgfm                  0.4.2            py37h0b31af3_2    conda-forge
coadd-mdetsims            0.1                       dev_0    <develop>
colour                    0.1.5                      py_0    conda-forge
compiler-rt               9.0.1                h6a512c6_0    conda-forge
compiler-rt_osx-64        9.0.1                h6a512c6_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
corner                    2.0.1                   py_1002    conda-forge
corrfunc                  2.3.2            py37he7c1ce5_1    conda-forge
cryptography              2.8              py37hafa8578_1    conda-forge
cx_oracle                 7.3.0            py37h0b31af3_0    conda-forge
cxx-compiler              1.0.4                h707564b_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
des-desmeds               0.9.8                    py37_0    conda-forge
des-easyaccess            1.4.7                    py37_2    conda-forge
descwl                    0.3.dev0                 pypi_0    pypi
descwl-shear-sims         0.1.0                     dev_0    <develop>
differentiable-smhm       0.0.dev0                  dev_0    <develop>
dill                      0.3.1.1                  py37_0    conda-forge
docutils                  0.16                     py37_0    conda-forge
editdistance              0.5.3            py37h4a8c4bd_0    conda-forge
eigen                     3.3.7             ha1b3eb9_1001    conda-forge
emcee                     3.0.2              pyh5ca1d4c_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
esutil                    0.6.4            py37h4f17bb1_0    conda-forge
expat                     2.2.5             h4a8c4bd_1004    conda-forge
fastcache                 1.1.0            py37h0b31af3_0    conda-forge
fftw                      3.3.8           nompi_h44ae4c8_1110    conda-forge
firecrown                 0.1.0                     dev_0    <develop>
fitsio                    1.0.5            py37h93e8f8d_0    conda-forge
flake8                    3.7.9                    py37_0    conda-forge
flask                     1.1.1                      py_1    conda-forge
flask-sqlalchemy          2.4.0                      py_0    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
furl                      2.1.0                      py_0    conda-forge
future                    0.18.2                   py37_0    conda-forge
galsim                    2.2.3            py37hc0fbbca_0    conda-forge
galsim-extra              0.1                      pypi_0    pypi
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
gfortran_impl_osx-64      7.3.0                hf4212f2_2    conda-forge
gfortran_osx-64           7.3.0                h22b1bf0_6    conda-forge
glib                      2.58.3          py37h577aef8_1002    conda-forge
globus-cli                1.11.0                     py_0    conda-forge
globus-sdk                1.8.0                      py_0    conda-forge
gmp                       6.2.0                h4a8c4bd_0    conda-forge
gmpy2                     2.1.0b1          py37h4160ff4_0    conda-forge
gnureadline               8.0.0            py37h1de35cc_0    conda-forge
graphviz                  2.42.3               h98dfb87_0    conda-forge
gsl                       2.6                  ha2d443c_0    conda-forge
h5py                      2.10.0          nompi_py37h106b333_101    conda-forge
halotools                 0.6             py37h4f17bb1_1000    conda-forge
hdf5                      1.10.5          nompi_h3e39495_1104    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
identify                  1.4.10                     py_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib_metadata        1.4.0                    py37_0    conda-forge
infinity                  1.4                        py_0    conda-forge
intervals                 0.8.1                      py_0    conda-forge
ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
ipyparallel               6.2.4                    py37_0    conda-forge
ipython                   7.11.1           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
isl                       0.19                          0    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jax                       0.1.57             pyh5ca1d4c_0    conda-forge
jaxlib                    0.1.37           py37h5ca1d4c_0    conda-forge
jedi                      0.15.2                   py37_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
jmespath                  0.9.4                      py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.4                    py37_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py37_0    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
jupyter_highlight_selected_word 0.2.0                 py37_1000    conda-forge
jupyter_latex_envs        1.4.4                 py37_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
keyring                   21.1.0                   py37_0    conda-forge
kiwisolver                1.1.0            py37ha1b3eb9_0    conda-forge
krb5                      1.16.4               h1752a42_0    conda-forge
ld64                      450.3                h3c32e8a_3    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  8.0.1                h770b8ee_1    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    9.0.1                         1    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm8                  8.0.1                h770b8ee_0    conda-forge
libllvm9                  9.0.1                ha1b3eb9_0    conda-forge
libopenblas               0.3.7                h3d69b6c_7    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libprotobuf               3.11.2               hd174df1_0    conda-forge
libsodium                 1.0.17               h01d97ff_0    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.1.0                ha78913b_3    conda-forge
libuv                     1.34.0               h0b31af3_0    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
libxslt                   1.1.33               h320ff13_0    conda-forge
line_profiler             3.0.2            py37ha1b3eb9_0    conda-forge
llvm-openmp               9.0.1                h28b9765_2    conda-forge
llvmlite                  0.31.0           py37h05045ef_0    conda-forge
lmfit                     1.0.0                      py_0    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
lsstdesc.coord            1.2.0            py37ha1b3eb9_0    conda-forge
lxml                      4.4.2            py37he54a443_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
markupsafe                1.1.1            py37h0b31af3_0    conda-forge
matplotlib                3.1.2                    py37_1    conda-forge
matplotlib-base           3.1.2            py37h11da6c2_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mdetsims                  0.1                       dev_0    <develop>
meds                      0.9.10           py37h3b54f70_0    conda-forge
memory_profiler           0.57.0                     py_0    conda-forge
metadetect                0.2.0                     dev_0    <develop>
mistune                   0.8.4           py37h0b31af3_1000    conda-forge
mock                      3.0.5                    py37_0    conda-forge
mof                       0.9.9                    pypi_0    pypi
montara                   0.1                       dev_0    <develop>
more-itertools            8.1.0                      py_0    conda-forge
mpc                       1.1.0             h4160ff4_1006    conda-forge
mpfr                      4.0.2                h44b798e_0    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.0.3            py37h8b5c983_0    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
mypy_extensions           0.4.3                    py37_0    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.3                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
ngmix                     1.3.7                    py37_0    conda-forge
ngmixer                   0.9.6                     dev_0    <develop>
nodeenv                   1.3.4                      py_0    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
nspr                      4.20              h0a44026_1000    conda-forge
nss                       3.47                 hcec2283_0    conda-forge
numba                     0.47.0           py37h4f17bb1_0    conda-forge
numexpr                   2.7.1            py37h4f17bb1_0    conda-forge
numpy                     1.17.5           py37hde6bac1_0    conda-forge
numpydoc                  0.9.2                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openmpi                   4.0.2                hed52333_2    conda-forge
openssl                   1.1.1d               h0b31af3_0    conda-forge
opt_einsum                3.1.0                      py_0    conda-forge
orderedmultidict          1.0.1                      py_0    conda-forge
packaging                 20.0                       py_0    conda-forge
pandas                    0.25.3           py37h4f17bb1_0    conda-forge
pandoc                    2.9.1.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.1                    py37_0    conda-forge
parsl                     0.9.0                      py_0    conda-forge
parso                     0.5.2                      py_0    conda-forge
passlib                   1.7.1                      py_0    conda-forge
pathspec                  0.7.0                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.43                 h4a8c4bd_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
phonenumbers              8.10.14                    py_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
piff                      0.3                      pypi_0    pypi
pillow                    7.0.0            py37h918e99a_0    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pixmappy                  0.2                      pypi_0    pypi
pkginfo                   1.5.0.1                    py_0    conda-forge
plotly                    4.4.1                      py_0    conda-forge
pluggy                    0.13.0                   py37_0    conda-forge
pre-commit                1.21.0                   py37_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
protobuf                  3.11.2           py37h4a8c4bd_0    conda-forge
psutil                    5.6.7            py37h0b31af3_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.1                      py_0    conda-forge
pybind11                  2.4.3            py37ha1b3eb9_1    conda-forge
pycamb                    1.1.0                    py37_1    conda-forge
pyccl                     2.0.0rc3         py37h3dc85bc_1    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pydot                     1.4.1                 py37_1001    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pylbfgs                   0.2.0.13         py37h0b31af3_0    conda-forge
pynacl                    1.3.0           py37h0b31af3_1001    conda-forge
pyopenssl                 19.1.0                   py37_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyqt                      5.12.3           py37he22c54c_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py37h0b31af3_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
pytables                  3.6.1            py37h6f8395a_1    conda-forge
pytest                    5.3.4                    py37_0    conda-forge
pytest-mpi                0.3                      pypi_0    pypi
pytest-runner             5.2                        py_0    conda-forge
python                    3.7.6                h5c2c468_2    conda-forge
python-daemon             2.2.4                    py37_0    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3              py37h0b31af3_0    conda-forge
pyzmq                     18.1.1           py37h4bf09a9_0    conda-forge
qt                        5.12.5               h1b46049_0    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
readme_renderer           24.0                       py_0    conda-forge
regex                     2020.1.8         py37h0b31af3_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
requests-toolbelt         0.9.1                      py_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
rhash                     1.3.6             h1de35cc_1001    conda-forge
ripgrep                   11.0.2               h01d97ff_3    conda-forge
sacc                      0.2.3                    pypi_0    pypi
schwimmbad                0.3.0                    py37_2    conda-forge
scikit-learn              0.22.1           py37h3dc85bc_1    conda-forge
scipy                     1.4.1            py37h82752d6_0    conda-forge
seaborn                   0.9.0                      py_2    conda-forge
send2trash                1.5.0                      py_0    conda-forge
sep                       1.0.3           py37h3b54f70_1001    conda-forge
setuptools                45.1.0                   py37_0    conda-forge
six                       1.14.0                   py37_0    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
soupsieve                 1.9.4                    py37_0    conda-forge
sphinx                    2.3.1                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
sqlalchemy                1.3.3            py37h01d97ff_0    conda-forge
sqlalchemy-utils          0.34.1                     py_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
srd-models                0.1                       dev_0    <develop>
statsmodels               0.11.0           py37h0b31af3_0    conda-forge
swig                      4.0.1                h6de7cb9_0    conda-forge
sympy                     1.5.1                    py37_1    conda-forge
tapi                      1000.10.8            ha1b3eb9_4    conda-forge
tblib                     1.6.0                      py_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thechopper                0.0.dev0                 pypi_0    pypi
tk                        8.6.10               hbbe82c9_0    conda-forge
toml                      0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h0b31af3_0    conda-forge
tqdm                      4.41.1                     py_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
treecorr                  4.0.10           py37h4a8c4bd_0    conda-forge
twine                     3.1.1                    py37_0    conda-forge
typed-ast                 1.4.1            py37h0b31af3_0    conda-forge
typeguard                 2.7.0                      py_0    conda-forge
typing_extensions         3.7.4.1                  py37_0    conda-forge
uncertainties             3.1.3                      py_0    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
virtualenv                16.7.5                     py_0    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.16.0                     py_0    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
wurlitzer                 2.0.0                    py37_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.2.2                h0b31af3_1    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zipp                      2.0.0                      py_1    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                he7fca8b_1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : anl
    active env location : /Users/Matt/miniconda3/envs/anl
            shell level : 2
       user config file : /Users/Matt/.condarc
 populated config files : /Users/Matt/.condarc
          conda version : 4.8.0
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/Matt/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/Matt/miniconda3/pkgs
                          /Users/Matt/.conda/pkgs
       envs directories : /Users/Matt/miniconda3/envs
                          /Users/Matt/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.0 requests/2.22.0 CPython/3.7.6 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : /Users/Matt/.netrc
           offline mode : False
```
</details>

**Comment by beckermr** [comment]
Yup, you need either astropy 3x or a bug fix needs to be pushed upstream

**Comment by bsipocz** [comment]
The fix for this has been merged in halotools master, so it will work with astropy 4.0 once the new release is out. 

cc @aphearin
